# Configuração do Prometheus para MedSafe

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'medsafe'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # MedSafe API
  - job_name: 'medsafe-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:9090']
        labels:
          service: 'api'
          env: 'production'

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'database'

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'cache'

  # Node Exporter (se houver)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'system'


